name: "Unit Tests"

on:
  push:
    branches: [ "master", "java21", "fibers" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    - name: Setup local maven cache
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: maven-cache-${{ hashFiles('**/pom.xml') }}
        
    - name: Run tests
      run: ./mvnw test
